CREATE TABLE articles (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	lat REAL NOT NULL,
	long REAL NOT NULL,
	keywords TEXT NOT NULL,
	section TEXT NOT NULL,
	desc TEXT,
	timestamp DATETIME NOT NULL,
	body TEXT UNIQUE NOT NULL
);
